//task
export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILED = 'FETCH_TASK_FAILED';

export const FILTER_TASK = 'FILTER_TASK';
export const FILTER_TASK_SUCCESS = 'FILTER_TASK_SUCCESS';
export const FILTER_TASK_FAILED = 'FILTER_TASK_FAILED';


//ui
export const SHOW_LOADING = 'SHOW_LOADDING';
export const HIDE_LOADING = 'HIDE_LOADDING';
